version: '3.8'
services:
  mongodb:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "6000:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - tablego-network

  tablego-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/tablego_db?authSource=admin
      - CORS_ORIGIN=http://localhost:8081
      - SESSION_SECRET=testsecret
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - tablego-network

  tablego-test:
    image: nginx:alpine
    container_name: tablego-test
    ports:
      - "8081:80"
    networks:
      - tablego-network

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tablego-network

volumes:
  mongo_data:
  jenkins_home:

networks:
  tablego-network:
    driver: bridge